import React from "react";
import type { Metadata } from "next";
import { Providers } from "./providers";
import "./globals.css";

export const metadata: Metadata = {
  title: "Holiday Deals",
  description: "Generated by Holiday Gremlin",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <React.StrictMode>
          <Providers>
            {children}
          </Providers>
        </React.StrictMode>
      </body>
    </html>
  );
}